version: '3'
services:
  db:
    image: mongo:latest
    container_name: mongoDb
    ports:
      - "27017:27017"
    networks:
      - migrationToolsNetwork

  migrationTools:
    image: avinetworks/avitools:22.1.4
    container_name: migrationTools
    tty: true
    volumes:
      - ./avi:/opt/avi
    networks:
      - migrationToolsNetwork
    ports:
      - "8080:3000"  # Map your application's port to host port
    depends_on:
      - db

networks:
  migrationToolsNetwork: